name: JiraViewer

options:
  bundleIdPrefix: com.mpi
  deploymentTarget:
    macOS: "13.0"

settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  JiraViewer:
    type: application
    platform: macOS

    sources:
      - path: .
        excludes:
          - "*.md"
          - ".git"
          - ".gitignore"
          - "project.yml"

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.mpi.JiraViewer
      INFOPLIST_FILE: Info.plist
      CODE_SIGN_ENTITLEMENTS: JiraViewer.entitlements
      DEVELOPMENT_TEAM: ""
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "13.0"
      ENABLE_HARDENED_RUNTIME: YES
      COMBINE_HIDPI_IMAGES: YES
      GENERATE_INFOPLIST_FILE: NO

    info:
      path: Info.plist

    entitlements:
      path: JiraViewer.entitlements
