//
//  SprintReview.swift
//  JiraViewer
//
//  Copyright © 2024-2026 Jonathan Gaffe. All rights reserved.
//  Licensed under the MIT License.
//

import Foundation

/// Sprint summary generated by business logic (domain entity)
struct SprintReview: Identifiable, Hashable {
    let id: String
    let sprintId: Int
    let sprintName: String
    let generatedAt: Date

    // Statistics
    let totalIssues: Int
    let doneIssues: Int
    let inProgressIssues: Int
    let todoIssues: Int
    let completionPercentage: Int

    // Distribution by type
    let issuesByType: [String: Int]
    let doneByType: [String: Int]

    // Time metrics
    let timeMetrics: TimeMetrics?

    // Insights
    let cycleTimeMetrics: CycleTimeMetrics?

    // Blocked issues
    let blockedIssuesMetrics: BlockedIssuesMetrics?

    // Status flow
    let statusFlowMetrics: StatusFlowMetrics?

    // Generated text
    let summaryText: String

    init(
        id: String = UUID().uuidString,
        sprintId: Int,
        sprintName: String,
        generatedAt: Date = Date(),
        totalIssues: Int,
        doneIssues: Int,
        inProgressIssues: Int,
        todoIssues: Int,
        completionPercentage: Int,
        issuesByType: [String: Int],
        doneByType: [String: Int],
        timeMetrics: TimeMetrics? = nil,
        cycleTimeMetrics: CycleTimeMetrics? = nil,
        blockedIssuesMetrics: BlockedIssuesMetrics? = nil,
        statusFlowMetrics: StatusFlowMetrics? = nil,
        summaryText: String
    ) {
        self.id = id
        self.sprintId = sprintId
        self.sprintName = sprintName
        self.generatedAt = generatedAt
        self.totalIssues = totalIssues
        self.doneIssues = doneIssues
        self.inProgressIssues = inProgressIssues
        self.todoIssues = todoIssues
        self.completionPercentage = completionPercentage
        self.issuesByType = issuesByType
        self.doneByType = doneByType
        self.timeMetrics = timeMetrics
        self.cycleTimeMetrics = cycleTimeMetrics
        self.blockedIssuesMetrics = blockedIssuesMetrics
        self.statusFlowMetrics = statusFlowMetrics
        self.summaryText = summaryText
    }
}

// MARK: - Nested Types

extension SprintReview {
    /// Time metrics based on time tracking
    struct TimeMetrics: Hashable {
        let totalTimeSpentHours: Double
        let totalEstimateHours: Double
        let doneTimeSpentHours: Double
        let averageTimePerTicketHours: Double
        let accuracyPercentage: Int

        var totalTimeSpentDays: Double {
            totalTimeSpentHours / 8.0
        }

        var isOverEstimated: Bool {
            accuracyPercentage > 120
        }

        var isUnderEstimated: Bool {
            accuracyPercentage < 80
        }

        var isAccurate: Bool {
            !isOverEstimated && !isUnderEstimated
        }
    }

    /// Cycle time metrics based on dates
    struct CycleTimeMetrics: Hashable {
        let averageCycleDays: Double
        let analyzedTicketsCount: Int
        let longestTicketKey: String
        let longestTicketDays: Double
    }

    /// Blocked issues metrics
    struct BlockedIssuesMetrics: Hashable {
        let blockedCount: Int
        let flaggedCount: Int
        let stagnantCount: Int
        let averageBlockedDays: Double
        let bottleneckStatus: String?
    }

    /// Status flow metrics - Time spent in each status/column
    struct StatusFlowMetrics: Hashable {
        let statusAverageDays: [String: Double]  // Average days per status
        let statusTicketCount: [String: Int]      // Number of tickets that went through each status
        let totalTicketsAnalyzed: Int
        let ticketDetails: [TicketStatusDetail]   // Detailed breakdown per ticket
    }

    /// Detail of time spent by a specific ticket in work statuses
    struct TicketStatusDetail: Hashable, Identifiable {
        let id: String  // ticket key
        let key: String
        let summary: String
        let timeInProgress: Double?      // Days in "In Progress"
        let timeInReview: Double?        // Days in "Review"
        let timeInTest: Double?          // Days in "Test"
        let currentStatus: String
        let isStuck: Bool                // True if spent > 3 days in any work status

        var totalWorkDays: Double {
            (timeInProgress ?? 0) + (timeInReview ?? 0) + (timeInTest ?? 0)
        }

        var slowestPhase: String? {
            let phases: [(String, Double)] = [
                ("In Progress", timeInProgress ?? 0),
                ("Review", timeInReview ?? 0),
                ("Test", timeInTest ?? 0)
            ]
            return phases.max(by: { $0.1 < $1.1 })?.0
        }
    }
}
